"""Canonical category names and cross-source mapping.

This is the join key for all sources. Keep it small and explicit: when a new
source label is seen, decide on the canonical name and add it here. No fuzzy
matching at runtime — drift in keys breaks the join silently.
"""
from __future__ import annotations

# Canonical category -> human-readable description
CANONICAL: dict[str, str] = {
    "analytics":            "Product / web analytics, dashboards",
    "ai-writing":           "AI writing, copy, content generation",
    "ai-coding":            "AI coding assistants, code review, dev tools",
    "billing":              "Subscription billing, invoicing, dunning",
    "crm":                  "CRM, contact management, sales pipelines",
    "customer-support":     "Help desk, ticketing, knowledge base",
    "email-marketing":      "Email campaigns, newsletters, drip",
    "forms":                "Forms, surveys, polls",
    "scheduling":           "Calendar, booking, appointments",
    "monitoring":           "Uptime, APM, log monitoring",
    "feedback":             "Customer feedback, NPS, in-product surveys",
    "knowledge-base":       "Wikis, internal docs, second-brain",
    "social-media":         "Social media scheduling, analytics",
    "seo":                  "SEO, keyword research, rank tracking",
    "video":                "Video editing, recording, hosting",
    "design":               "Design tools, mockups, prototyping",
    "automation":           "No-code workflows, integrations, iPaaS",
    "transactional-email":  "Transactional email, SMTP, deliverability",
    "auth":                 "Authentication, SSO, identity",
    "newsletter":           "Newsletter publishing platforms",
    "form-builder":         "Drag-and-drop form builders",
    "project-management":   "PM, kanban, task tracking",
    "time-tracking":        "Time tracking, timesheets",
    "invoicing":            "Invoice generation",
    "expense-tracking":     "Expense reports, receipts",
    "hr":                   "HRIS, payroll, onboarding",
    "documents":            "Document generation, e-signature",
    "feature-flags":        "Feature flags, A/B testing",
    "error-tracking":       "Crash reporting, error monitoring",
    "data-warehouse":       "Data warehousing, ETL",
    "bi":                   "BI, reporting, dashboards",
    "password-manager":     "Password managers, secrets",
    "backup":               "Backups, snapshots, archival",
    "file-sharing":         "File hosting, sync, sharing",
    "chat":                 "Team chat, messaging",
    "video-conferencing":   "Video meetings, conferencing",
    "podcast":              "Podcast hosting, editing",
    "screen-recording":     "Screen recording, async video",
    "transcription":        "Speech-to-text, transcription",
    "translation":          "Translation, localization",
    "image-generation":     "AI image generation",
    "code-search":          "Code search, dependency analysis",
}

# Mapping from external labels (lowercased) -> canonical. Build out as data is seen.
ALIASES: dict[str, str] = {
    "analytics":                       "analytics",
    "product analytics":               "analytics",
    "web analytics":                   "analytics",
    "dashboards":                      "analytics",
    "bi":                              "bi",
    "business intelligence":           "bi",
    "ai writing":                      "ai-writing",
    "copywriting":                     "ai-writing",
    "content generation":              "ai-writing",
    "ai code":                         "ai-coding",
    "ai coding":                       "ai-coding",
    "developer tools":                 "ai-coding",
    "developer-tools":                 "ai-coding",
    "billing":                         "billing",
    "subscription billing":            "billing",
    "invoicing":                       "invoicing",
    "crm":                             "crm",
    "sales":                           "crm",
    "customer support":                "customer-support",
    "help desk":                       "customer-support",
    "helpdesk":                        "customer-support",
    "ticketing":                       "customer-support",
    "email marketing":                 "email-marketing",
    "newsletters":                     "newsletter",
    "newsletter":                      "newsletter",
    "forms":                           "forms",
    "form builder":                    "form-builder",
    "surveys":                         "forms",
    "scheduling":                      "scheduling",
    "calendar":                        "scheduling",
    "appointments":                    "scheduling",
    "booking":                         "scheduling",
    "monitoring":                      "monitoring",
    "uptime":                          "monitoring",
    "apm":                             "monitoring",
    "logging":                         "monitoring",
    "feedback":                        "feedback",
    "nps":                             "feedback",
    "knowledge base":                  "knowledge-base",
    "wiki":                            "knowledge-base",
    "docs":                            "knowledge-base",
    "social media":                    "social-media",
    "social":                          "social-media",
    "seo":                             "seo",
    "video":                           "video",
    "video editing":                   "video",
    "design":                          "design",
    "prototyping":                     "design",
    "automation":                      "automation",
    "no-code":                         "automation",
    "ipaas":                           "automation",
    "transactional email":             "transactional-email",
    "email api":                       "transactional-email",
    "auth":                            "auth",
    "authentication":                  "auth",
    "sso":                             "auth",
    "identity":                        "auth",
    "project management":              "project-management",
    "kanban":                          "project-management",
    "time tracking":                   "time-tracking",
    "expense tracking":                "expense-tracking",
    "hr":                              "hr",
    "payroll":                         "hr",
    "documents":                       "documents",
    "e-signature":                     "documents",
    "esignature":                      "documents",
    "feature flags":                   "feature-flags",
    "a/b testing":                     "feature-flags",
    "ab testing":                      "feature-flags",
    "error tracking":                  "error-tracking",
    "crash reporting":                 "error-tracking",
    "data warehouse":                  "data-warehouse",
    "etl":                             "data-warehouse",
    "password manager":                "password-manager",
    "secrets management":              "password-manager",
    "backup":                          "backup",
    "backups":                         "backup",
    "file sharing":                    "file-sharing",
    "file hosting":                    "file-sharing",
    "chat":                            "chat",
    "team chat":                       "chat",
    "messaging":                       "chat",
    "video conferencing":              "video-conferencing",
    "podcast":                         "podcast",
    "screen recording":                "screen-recording",
    "loom alternatives":               "screen-recording",
    "transcription":                   "transcription",
    "translation":                     "translation",
    "image generation":                "image-generation",
    "code search":                     "code-search",
    # extra labels observed in real READMEs
    "web analytics":                   "analytics",
    "session replay":                  "analytics",
    "product analytics":               "analytics",
    "ai code completion":              "ai-coding",
    "code completion":                 "ai-coding",
    "team knowledge base":             "knowledge-base",
    "note-taking":                     "knowledge-base",
    "knowledge management":            "knowledge-base",
    "online forms":                    "forms",
    "online survey":                   "forms",
    "survey platform":                 "forms",
    "live chat":                       "customer-support",
    "customer engagement":             "customer-support",
    "ticket management":               "customer-support",
    "team communication":              "chat",
    "video conferencing":              "video-conferencing",
    "scheduling tool":                 "scheduling",
    "kanban board":                    "project-management",
    "to-do app":                       "project-management",
    "bug tracking":                    "error-tracking",
    "error tracking":                  "error-tracking",
    "feature management":              "feature-flags",
    "feature flag":                    "feature-flags",
    "log management":                  "monitoring",
    "auth & sso":                      "auth",
    "user authentication":             "auth",
    "password manager":                "password-manager",
    "personal cloud":                  "file-sharing",
    "cloud storage":                   "file-sharing",
    "email delivery":                  "transactional-email",
    "usage-based billing":             "billing",
    "subscription billing":            "billing",
    "document signing":                "documents",
    "workflow automation":             "automation",
    "integration platform":            "automation",
    "project management":              "project-management",
    "time tracking":                   "time-tracking",
    "customer data platform":          "analytics",
    "business intelligence":           "bi",
    "data warehouse":                  "data-warehouse",
    "cloud data warehouse":            "data-warehouse",
    "api gateway":                     "automation",
    "api platform":                    "automation",
    "community platform":              "chat",
    "cloud development environment":   "ai-coding",
    "enterprise search":               "code-search",
    "financial service":               "expense-tracking",
    "backend as a service":            "auth",
    "cms":                             "knowledge-base",
    "ecommerce":                       "billing",
    "e-commerce":                      "billing",
    "static site generator":           "knowledge-base",
    "static website generator":        "knowledge-base",
    "blogging platform":               "newsletter",
    "personal website builder":        "design",
    "website builder":                 "design",
    "icons":                           "design",
    "collaborative design tool":       "design",
    "link shortener":                  "automation",
    "online store builder":            "billing",
    "smart spreadsheet":               "knowledge-base",
    "internal tools":                  "automation",
    "company blogs":                   "newsletter",
    "company blogs/ newsletters":      "newsletter",
    "personal finance":                "expense-tracking",
    "ecommerce platform":              "billing",
    "digital search experience":       "code-search",
    "annotation":                      "knowledge-base",
    "graph database":                  "data-warehouse",
    "vector database":                 "data-warehouse",
    "time-series database":            "data-warehouse",
    "communication":                   "chat",
    "cybersecurity":                   "auth",
    "notification infrastructure":     "transactional-email",
    "api development":                 "ai-coding",
    "programmatic videos":             "video",
    "session replay and analytics":    "analytics",
    "content management system":       "knowledge-base",
}


def canonicalize(label: str) -> str | None:
    """Return canonical category name for an external label, or None if unmapped.

    Lookup order:
      1. exact match (lowercased)
      2. suffix-stripped exact match
      3. longest alias-key found as a substring (covers verbose labels like
         "Web analytics (Google Analytics alternatives):" -> "web analytics")
    """
    if not label:
        return None
    key = label.strip().lower().rstrip(":").strip()
    if key in ALIASES:
        return ALIASES[key]
    for suf in (" tools", " software", " platforms", " apps"):
        if key.endswith(suf):
            stripped = key[: -len(suf)]
            if stripped in ALIASES:
                return ALIASES[stripped]
    best_alias: str | None = None
    best_len = 0
    for alias, canon in ALIASES.items():
        if len(alias) >= 4 and len(alias) > best_len and alias in key:
            best_alias, best_len = canon, len(alias)
    return best_alias
